/**
 * One-off: reads ../../200道题.txt (from repo root) or path from argv
 * Outputs ../data/questions.js
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const defaultInput = path.join(root, '..', '200道题.txt');
const inputPath = process.argv[2] || defaultInput;
const outPath = path.join(root, 'data', 'questions.js');

const raw = fs.readFileSync(inputPath, 'utf8');
const lines = raw.split(/\r?\n/);

const DIM_RE = /^(.+?)【(S1|S2|S3|E1|E2|E3|A1|A2)】\s*$/;
const Q_RE = /^(\d+)\.\s*(.+)$/;

let currentModule = 1;
const questions = [];
let current = null;

function flush() {
  if (current && current.options.length === 4) {
    questions.push(current);
  }
  current = null;
}

for (const line of lines) {
  const t = line.trim();
  if (!t || t.startsWith('_')) continue;
  if (t.includes('一、基础学习场景')) {
    currentModule = 1;
    continue;
  }
  if (t.includes('二、补课与师生互动')) {
    currentModule = 2;
    continue;
  }
  if (t.includes('三、考试与成绩场景')) {
    currentModule = 3;
    continue;
  }
  if (t.includes('四、生活心态与学习习惯')) {
    currentModule = 4;
    continue;
  }
  if (t.startsWith('孩子学习人格') || t.startsWith('测试说明') || t.startsWith('本题库') || t.startsWith('人格对应表') || t.startsWith('测试题目')) continue;

  const qm = t.match(Q_RE);
  if (qm) {
    flush();
    const num = parseInt(qm[1], 10);
    current = {
      id: `q${num}`,
      module: currentModule,
      num,
      text: qm[2].trim(),
      options: []
    };
    continue;
  }

  const optPrefix = t.match(/^([A-D])\.\s*(.+)$/);
  if (optPrefix && current) {
    const body = optPrefix[2].trim();
    const dm = body.match(DIM_RE);
    if (!dm) {
      console.warn('Bad option line:', t);
      continue;
    }
    const label = dm[1].trim();
    const dim = dm[2];
    current.options.push({ label, dim, value: current.options.length + 1 });
  }
}

flush();

const byMod = [1, 2, 3, 4].map((m) => questions.filter((q) => q.module === m).length);
console.log('Parsed questions:', questions.length, 'per module:', byMod.join(','));

if (questions.length !== 200 || byMod.some((n) => n !== 50)) {
  console.error('Expected 200 questions, 50 per module');
  process.exitCode = 1;
}

const banner = `/* auto-generated by tools/parse-200.cjs — do not edit by hand */\n`;
const body = `const QUESTION_BANK = ${JSON.stringify(questions, null, 2)};\n`;
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, banner + body, 'utf8');
console.log('Wrote', outPath);
