-- 创建支付交易表
CREATE TABLE IF NOT EXISTS `fa_payments` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `order_no` varchar(50) NOT NULL COMMENT '订单编号',
  `tutor_order_id` int(11) DEFAULT NULL COMMENT '家教订单ID',
  `tutor_name` varchar(255) DEFAULT NULL COMMENT '家教名称',
  `teacher_name` varchar(100) DEFAULT NULL COMMENT '老师姓名',
  `teacher_id` int(11) DEFAULT NULL COMMENT '老师ID',
  `contact_student` varchar(100) DEFAULT NULL COMMENT '对接的同学',
  `amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '信息费金额',
  `deposit_amount` decimal(10,2) DEFAULT '0.00' COMMENT '收到课酬',
  `refund_apply_amount` decimal(10,2) DEFAULT '0.00' COMMENT '申请应退',
  `refunded_amount` decimal(10,2) DEFAULT '0.00' COMMENT '已退金额',
  `actual_amount` decimal(10,2) DEFAULT '0.00' COMMENT '实收金额',
  `payment_method` varchar(50) DEFAULT NULL COMMENT '支付方式',
  `payer_name` varchar(100) DEFAULT NULL COMMENT '付款人姓名',
  `payer_contact` varchar(50) DEFAULT NULL COMMENT '付款人联系方式',
  `transaction_id` varchar(100) DEFAULT NULL COMMENT '交易流水号',
  `status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT '支付状态：pending-待支付，paid-已支付，cancelled-已取消',
  `refund_status` varchar(20) DEFAULT NULL COMMENT '退款状态：pending-退款待处理，rejected-退款驳回，completed-已退费',
  `dispatcher_id` int(11) DEFAULT NULL COMMENT '派单员ID（关联admin表）',
  `refund_reason` text COMMENT '退款原因',
  `reject_reason` text COMMENT '驳回原因',
  `refund_voucher` text COMMENT '退款凭证（JSON格式）',
  `remark` text COMMENT '备注',
  `paid_time` datetime DEFAULT NULL COMMENT '支付时间',
  `refund_time` datetime DEFAULT NULL COMMENT '退款时间',
  `refund_apply_time` datetime DEFAULT NULL COMMENT '申请退款时间',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_no` (`order_no`),
  KEY `tutor_order_id` (`tutor_order_id`),
  KEY `teacher_id` (`teacher_id`),
  KEY `dispatcher_id` (`dispatcher_id`),
  KEY `status` (`status`),
  KEY `refund_status` (`refund_status`),
  KEY `paid_time` (`paid_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付交易表';
