-- 家长预约订单表
CREATE TABLE IF NOT EXISTS `fa_parent_orders` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `order_no` varchar(50) NOT NULL COMMENT '订单号',
  `admin_id` int(11) NOT NULL COMMENT '管理员ID',
  `grade` varchar(50) NOT NULL COMMENT '学员年级',
  `subject` varchar(100) NOT NULL COMMENT '辅导科目',
  `student_info` text NOT NULL COMMENT '学生情况',
  `frequency` varchar(200) NOT NULL COMMENT '辅导次数和频率',
  `teacher_requirement` text NOT NULL COMMENT '对老师要求',
  `address` varchar(500) NOT NULL COMMENT '授课地址',
  `parent_name` varchar(50) NOT NULL COMMENT '家长称呼',
  `parent_contact` varchar(100) NOT NULL COMMENT '联系方式',
  `remark` text COMMENT '备注信息',
  `status` enum('pending','approved','rejected') DEFAULT 'pending' COMMENT '订单状态：pending-待审核，approved-已通过，rejected-已拒绝',
  `reject_reason` text COMMENT '拒绝原因',
  `tutor_id` int(11) DEFAULT NULL COMMENT '关联的家教信息ID（审核通过后）',
  `audit_time` datetime DEFAULT NULL COMMENT '审核时间',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_no` (`order_no`),
  KEY `admin_id` (`admin_id`),
  KEY `status` (`status`),
  KEY `create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='家长预约订单表';
